Algoritmo "Exercicio 9"
//  Faça um algoritmo que leia quanto dinheiro uma pessoa tem na carteira (em R$)
// e mostre quantos dólares ela pode comprar. Considere US$1,00 = R$3,45.
Var

 m, re,dol: real


Inicio

      escreval("Olá, bem vindo!!")
      escreva ("Quanto dinheiro tem na carteira?(Em reais): R$")
      leia(re)

      dol <- re * 3,45

      escreval()
      escreval ("Com",re," reais, podemos comprar",dol," dolares")
      
Fimalgoritmo